### ISSUE TITLE
part_kmeans() error

### ISSUE THREAD

**Issue by millstei** [USCbiostats/partition#1]
Error from small threshold:

> 
> prt = partition( .data=x, threshold=.6, partitioner = part_kmeans() )
> prt = partition( .data=x, threshold=.2, partitioner = part_kmeans() )
Error in reduce_partition_c(.data, df = .data, assign_partition = assign_partition,  : 
  Evaluation error: 'x' must be an array of at least two dimensions.
>

**Comment by malcolmbarrett** [comment]
This turned out to be the same bug as you had before; data frames coerce to a vector when a single column is subset using df[, i], a default that drives me bananas. I've found all the places I do this and replaced with df[, i, drop = FALSE] to make it consistent, so this should now be truly resolved

**Comment by millstei** [comment]
Great. I will reinstall.


Josh

________________________________
